# Site settings
title: DSP

email: "leewk921223@gmail.com"
url: "http://kascia.github.io/"
github_url: "http://github.com/kascia/dsp"
github_editurl: "/blob/master"
github_profile: "http://github.com/kascia"
baseurl: "/dsp"
disqus_shortname: kascia

exclude:
  - README.md
  - _site

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
